// Model catalog for Hanzo pricing service.
//
// Zen model PRICING is fetched live from zen-gateway at sync time.
// Third-party models are detected DYNAMICALLY from OpenRouter.
// Only Zen catalog metadata (name, description, features, specs) lives here.

// ── Hanzo Zen model catalog — metadata only, no prices ──────────────
export const zenCatalog = [
  // Zen4 Generation
  {
    name: "zen4",
    fullName: "Zen4 — Flagship",
    description: "Flagship model for complex reasoning and multi-domain tasks.",
    features: ["202k context window", "Flagship intelligence"],
    tier: "ultra max",
    specs: { params: "~400B", arch: "Dense Transformer" },
  },
  {
    name: "zen4-pro",
    fullName: "Zen4 Pro — High Capability",
    description: "High-capability model with efficient MoE architecture for demanding workloads.",
    features: ["131k context window", "MoE architecture"],
    tier: "ultra",
    specs: { params: "80B (3B active)", arch: "MoE" },
  },
  {
    name: "zen4-max",
    fullName: "Zen4 Max — Extended Context",
    description: "Extended context MoE model for large document processing and analysis.",
    features: ["131k context window", "235B MoE parameters"],
    tier: "ultra",
    specs: { params: "235B (22B active)", arch: "MoE" },
  },
  {
    name: "zen4-mini",
    fullName: "Zen4 Mini — Fast & Efficient",
    description: "Lightweight model optimized for speed and cost efficiency.",
    features: ["40k context window", "Ultra-fast inference"],
    tier: "pro",
    specs: { params: "8B", arch: "Dense Transformer" },
  },
  {
    name: "zen4-ultra",
    fullName: "Zen4 Ultra — Maximum Reasoning",
    description: "Maximum reasoning capability with extended thinking for complex problems.",
    features: ["202k context window", "Deep reasoning"],
    tier: "ultra max",
    specs: { params: "~400B", arch: "Dense Transformer + CoT" },
  },
  {
    name: "zen4-thinking",
    fullName: "Zen4 Thinking — Deep Reasoning",
    description: "Dedicated reasoning model with explicit chain-of-thought capabilities.",
    features: ["131k context window", "Chain-of-thought"],
    tier: "pro max",
    specs: { params: "80B (3B active)", arch: "MoE + CoT" },
  },
  {
    name: "zen4-coder",
    fullName: "Zen4 Coder — Code Generation",
    description: "Code-specialized model for generation, review, and debugging.",
    features: ["262k context window", "480B MoE parameters"],
    tier: "ultra",
    specs: { params: "480B (35B active)", arch: "MoE" },
  },
  {
    name: "zen4-coder-flash",
    fullName: "Zen4 Coder Flash — Fast Code",
    description: "Lightweight code model optimized for speed and inline completions.",
    features: ["262k context window", "Fast inference"],
    tier: "pro max",
    specs: { params: "30B (3B active)", arch: "MoE" },
  },
  {
    name: "zen4-coder-pro",
    fullName: "Zen4 Coder Pro — Premium Code",
    description: "Full-precision code model for maximum accuracy on complex codebases.",
    features: ["262k context window", "BF16 full precision"],
    tier: "ultra max",
    specs: { params: "480B", arch: "Dense BF16" },
  },
  // Zen3 Generation
  {
    name: "zen3-omni",
    fullName: "Zen3 Omni — Hypermodal",
    description: "Multimodal model supporting text, vision, and structured output.",
    features: ["202k context window", "Multimodal"],
    tier: "pro max",
    specs: { params: "~200B", arch: "Dense Multimodal" },
  },
  {
    name: "zen3-vl",
    fullName: "Zen3 VL — Vision-Language",
    description: "Vision-language model for image understanding and visual reasoning.",
    features: ["131k context window", "Vision + language"],
    tier: "pro max",
    specs: { params: "30B (3B active)", arch: "MoE Vision-Language" },
  },
  {
    name: "zen3-nano",
    fullName: "Zen3 Nano — Edge",
    description: "Ultra-lightweight model for edge deployment and low-latency tasks.",
    features: ["40k context window", "4B parameters"],
    tier: "pro",
    specs: { params: "4B", arch: "Dense Transformer" },
  },
  {
    name: "zen3-guard",
    fullName: "Zen3 Guard — Content Safety",
    description: "Content safety classifier for moderation and guardrails.",
    features: ["40k context window", "Safety classifier"],
    tier: "pro",
    specs: { params: "4B", arch: "Dense Transformer" },
  },
  // Zen3 Embedding — via /v1/embeddings (Qwen3)
  {
    name: "zen3-embedding",
    fullName: "Zen3 Embedding — 8B",
    description: "High-quality text embeddings powered by Qwen3 for RAG, search, and classification.",
    features: ["40k context window", "8B parameters"],
    tier: "pro max",
    specs: { params: "8B", arch: "Qwen3 Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-medium",
    fullName: "Zen3 Embedding Medium — 4B",
    description: "Balanced embedding model for cost-effective retrieval workloads.",
    features: ["40k context window", "4B parameters"],
    tier: "pro",
    specs: { params: "4B", arch: "Qwen3 Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-small",
    fullName: "Zen3 Embedding Small — 0.6B",
    description: "Lightweight embedding model for high-throughput, low-cost applications.",
    features: ["32k context window", "0.6B parameters"],
    tier: "starter",
    specs: { params: "0.6B", arch: "Qwen3 Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-openai",
    fullName: "Zen3 Embedding OpenAI — Compatible",
    description: "OpenAI-compatible embedding endpoint for drop-in migration.",
    features: ["8k context window", "3072 dimensions"],
    tier: "pro max",
    specs: { params: "N/A", arch: "OpenAI Embedding" },
    endpoint: "/v1/embeddings",
  },
  // Zen3 Reranker — via /v1/rerank (Qwen3)
  {
    name: "zen3-reranker",
    fullName: "Zen3 Reranker — 8B",
    description: "High-quality reranker for improving retrieval accuracy in RAG pipelines.",
    features: ["40k context window", "8B parameters"],
    tier: "pro max",
    specs: { params: "8B", arch: "Qwen3 Reranker" },
    endpoint: "/v1/rerank",
  },
  {
    name: "zen3-reranker-medium",
    fullName: "Zen3 Reranker Medium — 4B",
    description: "Balanced reranker for cost-effective retrieval quality improvement.",
    features: ["40k context window", "4B parameters"],
    tier: "pro",
    specs: { params: "4B", arch: "Qwen3 Reranker" },
    endpoint: "/v1/rerank",
  },
  {
    name: "zen3-reranker-small",
    fullName: "Zen3 Reranker Small — 0.6B",
    description: "Lightweight reranker for high-throughput reranking at minimal cost.",
    features: ["40k context window", "0.6B parameters"],
    tier: "starter",
    specs: { params: "0.6B", arch: "Qwen3 Reranker" },
    endpoint: "/v1/rerank",
  },
  // Zen3 Image — via /v1/images/generations (FLUX, SDXL, etc.)
  {
    name: "zen3-image",
    fullName: "Zen3 Image — FLUX Kontext Pro",
    description: "Best general-purpose image generation with FLUX Kontext Pro.",
    features: ["Text-to-image", "Image editing"],
    tier: "pro max",
    specs: { params: "N/A", arch: "FLUX Kontext Pro" },
    endpoint: "/v1/images/generations",
    pricingUnit: "image",
    staticPricing: { perUnit: 0.04 },
  },
  {
    name: "zen3-image-max",
    fullName: "Zen3 Image Max — FLUX Kontext Max",
    description: "Maximum quality image generation for professional creative work.",
    features: ["Text-to-image", "Maximum quality"],
    tier: "ultra max",
    specs: { params: "N/A", arch: "FLUX Kontext Max" },
    endpoint: "/v1/images/generations",
    pricingUnit: "image",
    staticPricing: { perUnit: 0.08 },
  },
  {
    name: "zen3-image-dev",
    fullName: "Zen3 Image Dev — FLUX.1 [dev]",
    description: "FLUX development model for experimentation and iteration.",
    features: ["Text-to-image", "Development"],
    tier: "pro",
    specs: { params: "N/A", arch: "FLUX.1 [dev]" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.0005 },
  },
  {
    name: "zen3-image-fast",
    fullName: "Zen3 Image Fast — FLUX.1 [schnell]",
    description: "Fastest FLUX model for real-time image generation.",
    features: ["Text-to-image", "Ultra-fast"],
    tier: "pro",
    specs: { params: "N/A", arch: "FLUX.1 [schnell]" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00035 },
  },
  {
    name: "zen3-image-sdxl",
    fullName: "Zen3 Image SDXL — Stable Diffusion XL",
    description: "Stable Diffusion XL for high-resolution image generation.",
    features: ["Text-to-image", "1024px"],
    tier: "pro",
    specs: { params: "N/A", arch: "SDXL 1.0" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-playground",
    fullName: "Zen3 Image Playground — Playground v2.5",
    description: "Playground v2.5 aesthetic model for artistic image generation.",
    features: ["Text-to-image", "Aesthetic"],
    tier: "pro",
    specs: { params: "N/A", arch: "Playground v2.5" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-ssd",
    fullName: "Zen3 Image SSD — Segmind SSD-1B",
    description: "Fastest SDXL-compatible model for real-time generation.",
    features: ["Text-to-image", "Fastest SDXL"],
    tier: "starter",
    specs: { params: "1B", arch: "SSD-1B" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-jp",
    fullName: "Zen3 Image JP — Japanese SDXL",
    description: "Japanese-specialized Stable Diffusion XL model.",
    features: ["Text-to-image", "Japanese"],
    tier: "pro",
    specs: { params: "N/A", arch: "Japanese SDXL" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  // Zen3 Audio — via /v1/audio/transcriptions (Whisper, ASR)
  {
    name: "zen3-audio",
    fullName: "Zen3 Audio — Whisper V3 Large",
    description: "Best quality speech-to-text with Whisper V3 Large.",
    features: ["Multi-language", "Best accuracy"],
    tier: "pro max",
    specs: { params: "N/A", arch: "Whisper V3 Large" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0015 },
  },
  {
    name: "zen3-audio-fast",
    fullName: "Zen3 Audio Fast — Whisper V3 Turbo",
    description: "Fastest speech-to-text with Whisper V3 Turbo.",
    features: ["Multi-language", "Fastest"],
    tier: "pro",
    specs: { params: "N/A", arch: "Whisper V3 Turbo" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0009 },
  },
  {
    name: "zen3-asr",
    fullName: "Zen3 ASR — Streaming ASR v2",
    description: "Real-time streaming speech recognition for live transcription.",
    features: ["Streaming", "Real-time"],
    tier: "pro max",
    specs: { params: "N/A", arch: "Streaming ASR v2" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0035 },
  },
  {
    name: "zen3-asr-v1",
    fullName: "Zen3 ASR v1 — Streaming ASR v1",
    description: "First-generation streaming ASR for legacy compatibility.",
    features: ["Streaming", "Legacy"],
    tier: "pro",
    specs: { params: "N/A", arch: "Streaming ASR v1" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0032 },
  },
];

// ── Featured third-party model IDs (pinned to top of third-party list) ──
// These are detected from OpenRouter — IDs must match OpenRouter model IDs.
export const featuredModelIds = [
  "anthropic/claude-opus-4.6",
  "anthropic/claude-sonnet-4.6",
  "anthropic/claude-haiku-4.5",
  "openai/gpt-5",
  "openai/gpt-5-mini",
  "google/gemini-2.5-pro",
  "deepseek/deepseek-r1",
  "deepseek/deepseek-chat",
  "meta-llama/llama-4-maverick",
  "mistralai/mistral-large-2512",
  "cohere/command-a",
  "x-ai/grok-3",
];

// ── Static tool pricing ─────────────────────────────────────────────
export const toolPricing = [
  { name: "Web Search", unit: "per query", price: 0.005 },
  { name: "Code Interpreter", unit: "per session minute", price: 0.03 },
  { name: "File Storage", unit: "per GB/month", price: 0.20 },
  { name: "Image Generation", unit: "per image", price: 0.04 },
  { name: "Speech-to-Text", unit: "per minute", price: 0.006 },
  { name: "Text-to-Speech", unit: "per 1M characters", price: 15.0 },
];

// ── Static infrastructure pricing ───────────────────────────────────
export const computeTiers = [
  { name: "Starter", vcpus: 1, memory: "2 GB", storage: "50 GB", price: 8.4 },
  { name: "Basic", vcpus: 2, memory: "4 GB", storage: "80 GB", price: 21.6 },
  { name: "Standard", vcpus: 4, memory: "8 GB", storage: "160 GB", price: 57.6 },
  { name: "Professional", vcpus: 8, memory: "16 GB", storage: "320 GB", price: 115.2 },
  { name: "Enterprise", vcpus: 16, memory: "32 GB", storage: "640 GB", price: 230.4 },
];

export const gpuTiers = [
  { name: "GPU Standard", gpu: "1x H100", vram: "80 GB", price: 3.48 },
  { name: "GPU Pro", gpu: "2x H100", vram: "160 GB", price: 6.96 },
  { name: "GPU Ultra", gpu: "4x H100", vram: "320 GB", price: 13.92 },
];
