// Model catalog for Hanzo pricing service.
//
// Zen model PRICING is fetched live from zen-gateway at sync time.
// Third-party models are detected DYNAMICALLY from OpenRouter.
// Only Zen catalog metadata (name, description, features, specs) lives here.
//
// BRAND POLICY: Never expose upstream model names. Zen models are our own.

// ── Hanzo Zen model catalog — metadata only, no prices ──────────────
export const zenCatalog = [
  // Zen4 Generation
  {
    name: "zen4",
    fullName: "Zen4 — Flagship",
    description: "Flagship MoE model for complex reasoning and multi-domain tasks.",
    features: ["202K context window", "Flagship intelligence", "100+ languages"],
    tier: "ultra max",
    context: 202000,
    specs: { params: "744B (40B active)", arch: "MoE" },
  },
  {
    name: "zen4-ultra",
    fullName: "Zen4 Ultra — Maximum Reasoning",
    description: "Maximum reasoning capability with extended chain-of-thought on MoE architecture.",
    features: ["262K context window", "Deep reasoning", "Chain-of-thought"],
    tier: "ultra max",
    context: 262000,
    specs: { params: "744B (40B active)", arch: "MoE + CoT" },
  },
  {
    name: "zen4-pro",
    fullName: "Zen4 Pro — High Capability",
    description: "Efficient MoE model for demanding workloads with strong reasoning at production-grade cost.",
    features: ["131K context window", "MoE architecture"],
    tier: "ultra",
    context: 131000,
    specs: { params: "80B (3B active)", arch: "MoE" },
  },
  {
    name: "zen4-max",
    fullName: "Zen4 Max — Maximum Intelligence",
    description: "Most capable model for complex reasoning, analysis, and agentic tasks. 1M token context window.",
    features: ["1M context window", "Maximum intelligence", "Agentic coding"],
    tier: "ultra max",
    context: 1000000,
    specs: { params: "N/A", arch: "Dense" },
  },
  {
    name: "zen4-mini",
    fullName: "Zen4 Mini — Fast & Efficient",
    description: "Ultra-fast lightweight model optimized for speed and cost efficiency. Ideal for free tier.",
    features: ["128K context window", "Ultra-fast inference", "Free tier"],
    tier: "starter",
    context: 128000,
    specs: { params: "N/A", arch: "Dense" },
  },
  {
    name: "zen4-thinking",
    fullName: "Zen4 Thinking — Deep Reasoning",
    description: "Dedicated reasoning model with explicit chain-of-thought capabilities.",
    features: ["131K context window", "Chain-of-thought"],
    tier: "pro max",
    context: 131000,
    specs: { params: "80B (3B active)", arch: "MoE + CoT" },
  },
  // Zen4 Code
  {
    name: "zen4-coder",
    fullName: "Zen4 Coder — Code Generation",
    description: "Code-specialized MoE model for generation, review, debugging, and agentic programming.",
    features: ["163K context window", "All major languages"],
    tier: "ultra",
    context: 163000,
    specs: { params: "480B (35B active)", arch: "MoE" },
  },
  {
    name: "zen4-coder-pro",
    fullName: "Zen4 Coder Pro — Premium Code",
    description: "Full-precision BF16 code model for maximum accuracy on complex codebases.",
    features: ["131K context window", "BF16 full precision"],
    tier: "ultra max",
    context: 131000,
    specs: { params: "480B", arch: "Dense BF16" },
  },
  {
    name: "zen4-coder-flash",
    fullName: "Zen4 Coder Flash — Fast Code",
    description: "Lightweight code model optimized for speed and inline completions.",
    features: ["262K context window", "Fast inference"],
    tier: "pro max",
    context: 262000,
    specs: { params: "30B (3B active)", arch: "MoE" },
  },
  // Zen3 Generation — Chat
  {
    name: "zen3-omni",
    fullName: "Zen3 Omni — Hypermodal",
    description: "Multimodal model supporting text, vision, audio, and structured output.",
    features: ["202K context window", "Text + Vision + Audio"],
    tier: "pro max",
    context: 202000,
    specs: { params: "~200B", arch: "Dense Multimodal" },
  },
  {
    name: "zen3-vl",
    fullName: "Zen3 VL — Vision-Language",
    description: "Vision-language model for image understanding and visual reasoning.",
    features: ["262K context window", "Vision + Language"],
    tier: "pro max",
    context: 262000,
    specs: { params: "30B (3B active)", arch: "MoE Vision-Language" },
  },
  {
    name: "zen3-nano",
    fullName: "Zen3 Nano — Edge",
    description: "Ultra-lightweight model for edge deployment and low-latency tasks. Available on free tier.",
    features: ["128K context window", "8B parameters", "Free tier"],
    tier: "starter",
    context: 128000,
    specs: { params: "8B", arch: "Dense" },
  },
  {
    name: "zen3-guard",
    fullName: "Zen3 Guard — Content Safety",
    description: "Content safety classifier for moderation and guardrails. 9 safety categories, 119 languages.",
    features: ["65K context window", "Safety classifier"],
    tier: "pro",
    context: 65000,
    specs: { params: "4B", arch: "Dense" },
  },
  // Zen3 Embedding — via /v1/embeddings
  {
    name: "zen3-embedding",
    fullName: "Zen3 Embedding",
    description: "High-quality text embeddings for RAG, search, and classification.",
    features: ["8K context window", "3072 dimensions"],
    tier: "pro max",
    context: 8000,
    specs: { params: "N/A", arch: "Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-medium",
    fullName: "Zen3 Embedding Medium",
    description: "Balanced embedding model for cost-effective retrieval workloads.",
    features: ["40K context window", "4B parameters"],
    tier: "pro",
    context: 40000,
    specs: { params: "4B", arch: "Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-small",
    fullName: "Zen3 Embedding Small",
    description: "Lightweight embedding model for high-throughput, low-cost applications.",
    features: ["32K context window", "0.6B parameters"],
    tier: "starter",
    context: 32000,
    specs: { params: "0.6B", arch: "Embedding" },
    endpoint: "/v1/embeddings",
  },
  {
    name: "zen3-embedding-openai",
    fullName: "Zen3 Embedding — OpenAI Compatible",
    description: "OpenAI-compatible embedding endpoint for drop-in migration.",
    features: ["8K context window", "3072 dimensions"],
    tier: "pro max",
    context: 8000,
    specs: { params: "N/A", arch: "Embedding" },
    endpoint: "/v1/embeddings",
  },
  // Zen3 Reranker — via /v1/rerank
  {
    name: "zen3-reranker",
    fullName: "Zen3 Reranker",
    description: "High-quality reranker for improving retrieval accuracy in RAG pipelines.",
    features: ["40K context window", "8B parameters"],
    tier: "pro max",
    context: 40000,
    specs: { params: "8B", arch: "Reranker" },
    endpoint: "/v1/rerank",
  },
  {
    name: "zen3-reranker-medium",
    fullName: "Zen3 Reranker Medium",
    description: "Balanced reranker for cost-effective retrieval quality improvement.",
    features: ["40K context window", "4B parameters"],
    tier: "pro",
    context: 40000,
    specs: { params: "4B", arch: "Reranker" },
    endpoint: "/v1/rerank",
  },
  {
    name: "zen3-reranker-small",
    fullName: "Zen3 Reranker Small",
    description: "Lightweight reranker for high-throughput reranking at minimal cost.",
    features: ["40K context window", "0.6B parameters"],
    tier: "starter",
    context: 40000,
    specs: { params: "0.6B", arch: "Reranker" },
    endpoint: "/v1/rerank",
  },
  // Zen3 Image — via /v1/images/generations
  {
    name: "zen3-image",
    fullName: "Zen3 Image",
    description: "Best general-purpose image generation.",
    features: ["Text-to-image", "Image editing"],
    tier: "pro max",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "image",
    staticPricing: { perUnit: 0.04 },
  },
  {
    name: "zen3-image-max",
    fullName: "Zen3 Image Max",
    description: "Maximum quality image generation for professional creative work.",
    features: ["Text-to-image", "Maximum quality"],
    tier: "ultra max",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "image",
    staticPricing: { perUnit: 0.08 },
  },
  {
    name: "zen3-image-dev",
    fullName: "Zen3 Image Dev",
    description: "Development model for experimentation and iteration.",
    features: ["Text-to-image", "Development"],
    tier: "pro",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.0005 },
  },
  {
    name: "zen3-image-fast",
    fullName: "Zen3 Image Fast",
    description: "Fastest image model for real-time generation.",
    features: ["Text-to-image", "Ultra-fast"],
    tier: "pro",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00035 },
  },
  {
    name: "zen3-image-sdxl",
    fullName: "Zen3 Image SDXL",
    description: "High-resolution image generation at 1024px.",
    features: ["Text-to-image", "1024px"],
    tier: "pro",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-playground",
    fullName: "Zen3 Image Playground",
    description: "Aesthetic model for artistic image generation.",
    features: ["Text-to-image", "Aesthetic"],
    tier: "pro",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-ssd",
    fullName: "Zen3 Image SSD",
    description: "Fastest diffusion model for real-time generation.",
    features: ["Text-to-image", "Fastest"],
    tier: "starter",
    specs: { params: "1B", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  {
    name: "zen3-image-jp",
    fullName: "Zen3 Image JP",
    description: "Japanese-specialized image generation model.",
    features: ["Text-to-image", "Japanese"],
    tier: "pro",
    specs: { params: "N/A", arch: "Diffusion" },
    endpoint: "/v1/images/generations",
    pricingUnit: "step",
    staticPricing: { perUnit: 0.00013 },
  },
  // Zen3 Audio — via /v1/audio/transcriptions
  {
    name: "zen3-audio",
    fullName: "Zen3 Audio",
    description: "Best quality speech-to-text transcription.",
    features: ["Multi-language", "Best accuracy"],
    tier: "pro max",
    specs: { params: "N/A", arch: "ASR" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0015 },
  },
  {
    name: "zen3-audio-fast",
    fullName: "Zen3 Audio Fast",
    description: "Fastest speech-to-text transcription.",
    features: ["Multi-language", "Fastest"],
    tier: "pro",
    specs: { params: "N/A", arch: "ASR" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0009 },
  },
  {
    name: "zen3-asr",
    fullName: "Zen3 ASR",
    description: "Real-time streaming speech recognition for live transcription.",
    features: ["Streaming", "Real-time"],
    tier: "pro max",
    specs: { params: "N/A", arch: "Streaming ASR" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0035 },
  },
  {
    name: "zen3-asr-v1",
    fullName: "Zen3 ASR v1",
    description: "First-generation streaming ASR for legacy compatibility.",
    features: ["Streaming", "Legacy"],
    tier: "pro",
    specs: { params: "N/A", arch: "Streaming ASR" },
    endpoint: "/v1/audio/transcriptions",
    pricingUnit: "minute",
    staticPricing: { perUnit: 0.0032 },
  },
];

// ── Featured third-party model IDs (pinned to top of third-party list) ──
// These are detected from OpenRouter — IDs must match OpenRouter model IDs.
export const featuredModelIds = [
  "anthropic/claude-opus-4.6",
  "anthropic/claude-sonnet-4.6",
  "anthropic/claude-haiku-4.5",
  "openai/gpt-5",
  "openai/gpt-5-mini",
  "google/gemini-2.5-pro",
  "deepseek/deepseek-r1",
  "deepseek/deepseek-chat",
  "meta-llama/llama-4-maverick",
  "mistralai/mistral-large-2512",
  "cohere/command-a",
  "x-ai/grok-3",
];

// ── Static tool pricing ─────────────────────────────────────────────
export const toolPricing = [
  { name: "Web Search", unit: "per query", price: 0.005 },
  { name: "Code Interpreter", unit: "per session minute", price: 0.03 },
  { name: "File Storage", unit: "per GB/month", price: 0.20 },
  { name: "Image Generation", unit: "per image", price: 0.04 },
  { name: "Speech-to-Text", unit: "per minute", price: 0.006 },
  { name: "Text-to-Speech", unit: "per 1M characters", price: 15.0 },
];

// ── Compute presets mapped to real DO droplet slugs ─────────────────
// Base prices fetched from DO API at sync time; markup applied on top.
export const computePresets = [
  { id: "starter", name: "Starter", slug: "s-1vcpu-2gb", description: "Light tasks, chat bots, simple automations" },
  { id: "pro", name: "Pro", slug: "s-2vcpu-4gb", description: "Code generation, research, multi-tool agents" },
  { id: "power", name: "Power", slug: "s-4vcpu-8gb", description: "Heavy workloads, browser automation, large projects" },
  { id: "gpu", name: "GPU", slug: "g-2vcpu-8gb", description: "ML training, image generation, video processing" },
];

// Full DO droplet catalog (all sizes we support).
export const doDropletSlugs = [
  "s-1vcpu-1gb", "s-1vcpu-2gb", "s-2vcpu-2gb", "s-2vcpu-4gb",
  "s-4vcpu-8gb", "s-8vcpu-16gb", "s-16vcpu-32gb",
  "g-2vcpu-8gb", "g-4vcpu-16gb",
  "c-2vcpu-4gb", "c-4vcpu-8gb",
];

// Fallback prices if DO API is unreachable (actual DO prices as of 2026-02).
export const doFallbackPrices = {
  "s-1vcpu-1gb":   { vcpus: 1,  memoryMB: 1024,  diskGB: 25,  priceMonthly: 6,   priceHourly: 0.00893 },
  "s-1vcpu-2gb":   { vcpus: 1,  memoryMB: 2048,  diskGB: 50,  priceMonthly: 12,  priceHourly: 0.01786 },
  "s-2vcpu-2gb":   { vcpus: 2,  memoryMB: 2048,  diskGB: 60,  priceMonthly: 18,  priceHourly: 0.02679 },
  "s-2vcpu-4gb":   { vcpus: 2,  memoryMB: 4096,  diskGB: 80,  priceMonthly: 24,  priceHourly: 0.03571 },
  "s-4vcpu-8gb":   { vcpus: 4,  memoryMB: 8192,  diskGB: 160, priceMonthly: 48,  priceHourly: 0.07143 },
  "s-8vcpu-16gb":  { vcpus: 8,  memoryMB: 16384, diskGB: 320, priceMonthly: 96,  priceHourly: 0.14286 },
  "s-16vcpu-32gb": { vcpus: 16, memoryMB: 32768, diskGB: 640, priceMonthly: 192, priceHourly: 0.28571 },
  "g-2vcpu-8gb":   { vcpus: 2,  memoryMB: 8192,  diskGB: 25,  priceMonthly: 48,  priceHourly: 0.07143 },
  "g-4vcpu-16gb":  { vcpus: 4,  memoryMB: 16384, diskGB: 50,  priceMonthly: 96,  priceHourly: 0.14286 },
  "c-2vcpu-4gb":   { vcpus: 2,  memoryMB: 4096,  diskGB: 25,  priceMonthly: 40,  priceHourly: 0.05952 },
  "c-4vcpu-8gb":   { vcpus: 4,  memoryMB: 8192,  diskGB: 50,  priceMonthly: 80,  priceHourly: 0.11905 },
};

// GPU tiers (H100s not on DO standard API — kept static).
export const gpuTiers = [
  { name: "GPU Standard", gpu: "1x H100", vram: "80 GB", price: 3.48 },
  { name: "GPU Pro", gpu: "2x H100", vram: "160 GB", price: 6.96 },
  { name: "GPU Ultra", gpu: "4x H100", vram: "320 GB", price: 13.92 },
];
